### ISSUE TITLE
HTTPServer loops on shutdown under Linux

### ISSUE THREAD

**Issue by SARTrack** [IndySockets/Indy#375]
The HTTPServer loops on shutdown, and locks up the application's shutdown processes, only under Linux. 
This is a permanent issue, and urgently need to be fixed.

I used Delphi 10.4, compiling for Linux. Another user found the same problem in Lazarus.

Steps:
- Start a IdHTTPserver
- Make at least one connection to it
- Shutdown the server.
It loops in "TerminateAllYarns", as per debug log here:

Sep  1 07:37:47 debian11 sartrackserver[33098]: IdScheduler.TerminateAllYarns loop: Count=1
Sep  1 07:37:47 debian11 sartrackserver[33098]: IdSchedulerOfThread.TerminateYarn
Sep  1 07:37:47 debian11 sartrackserver[33098]: IdSchedulerOfThread.TerminateYarn calls LThread.Stop
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdScheduler.TerminateAllYarns DONE
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdScheduler.TerminateAllYarns loop: Count=1
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdSchedulerOfThread.TerminateYarn
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdSchedulerOfThread.TerminateYarn calls LThread.Stop
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdScheduler.TerminateAllYarns DONE
Sep  1 07:37:48 debian11 sartrackserver[33098]: IdScheduler.TerminateAllYarns loop: Count=1
Etc...

In de code:
procedure TIdSchedulerOfThread.TerminateYarn(AYarn: TIdYarn);
var
  LYarn: TIdYarnOfThread;
  LThread: TIdThreadWithTask;
begin
  // Bart
  syslog(LOG_NOTICE, 'IdSchedulerOfThread.TerminateYarn');
  Assert(AYarn<>nil);
  LYarn := TIdYarnOfThread(AYarn);
  LThread := LYarn.Thread;
  if (LThread <> nil) and (not LThread.Suspended) then begin
    // Is still running and will free itself
    syslog(LOG_NOTICE, 'IdSchedulerOfThread.TerminateYarn calls LThread.Stop');
    LThread.Stop;
    // Dont free the yarn. The thread frees it (IdThread.pas)
  end else
  begin
    // If suspended, was created but never started
    // ie waiting on connection accept

    // RLebeau: free the yarn here as well. This allows TIdSchedulerOfThreadPool
    // to put the suspended thread, if present, back in the pool.
    syslog(LOG_NOTICE, 'IdSchedulerOfThread.TerminateYarn calls IdDisposeAndNil(LYarn)');
    IdDisposeAndNil(LYarn);
  end;
end;

Another user found a work-around by enabling 'assertions' when not in Debug mode, but he was using Lazarus.

**Comment by rlebeau** [comment]
This was recently discussed on StackOverflow and AToZed forums:

https://stackoverflow.com/questions/68990738/
https://www.atozed.com/forums/thread-2432.html

As I stated on StackOverflow:

> `TerminateYarn()` simply signals the thread to terminate itself, and then the list gets unlocked. The thread will destroy itself when it stops running, which will destroy the associated `TIdYarn`, which will remove itself from the list.
>
> ...
>
> `TerminateYarn()` is not supposed to free the `Yarn` object while its owning thread is still running. That is why `TerminateYarn()` signals the thread to stop instead. The thread will free the `Yarn` when the thread object is destroyed, after it stops running. I stated that 2 days ago in my very first comment. **So my diagnosis is still the same - the thread is being blocked from terminating properly, that is why your server shutdown is hanging. You have not figured out yet where that blockage actually is.**

So, I am still of the opinion that this is NOT an issue with Indy itself, but that some piece of code that is running in the context of Yarn's owning thread has become deadlocked and thus is preventing the thread from fully terminating, thus blocking the server's shutdown.

**Comment by SARTrack** [comment]
Remy, I do not know how I can make this any more clear. 
This is a permanent problem with the basic HTTPServer, and has nothing to do with any other code. 
As I said:
- Create and Start a IdHTTPServer
- Make a single connection to it
- Close the server. It hangs.
It was also just reported by another users who programs in Lazarus.

I am *not* an Indy developer, and I do not understand a lot of the code. This problem can only be resolved by someone who understands the Indy code.

**Comment by rlebeau** [comment]
I don't doubt the steps you are using to reproduce a SIDE EFFECT of the problem (shutdown hangs).  But I have no doubt that you are LOOKING IN THE WRONG PLACE for the ROOT CAUSE of the problem (thread deadlock).  That is what you need to be focusing on instead.

I am an Indy developer, but I have no way to diagnose this myself right now, as I don't have a working compiler installed at the moment, but even if I did I am not a Linux user, I have no experience with Linux development, and so I couldn't test this even if I wanted to.

**Comment by rlebeau** [comment]
Just out of curiosity, can you re-test this now that #218 has been fixed?

**Comment by SARTrack** [comment]
The fix of #218 was already applied in my version of the Indy code, and the problem still persists in the HTTPServer. I will do a bit more testing today.

**Comment by SARTrack** [comment]
I just discovered that when I set "IdHTTPServer1.KeepAlive := false" the problem does not occur.
By default it is set to TRUE because the page is automatically updated every 15 seconds.
But, I guess that if the shutdown occurs just when a client is connected, it may still lock up then.

If anybody has some idea where I could change things to test, let me know.

**Comment by rlebeau** [comment]
If `KeepAlive` is false, `TIdHTTPServer` closes the client connection after sending a response.  Otherwise, it loops back and waits indefinitely (well, up to the `ReadTimeout`, anyway) for the client to send a new request.  `TIdHTTPServer` does not currently implement support for the `Keep-Alive` response header to limit the wait time (work in progress), but a server shutdown SHOULD cancel that wait, but it sounds like maybe it is not?

**Comment by SARTrack** [comment]
So where do I find that "wait", and where should it be canceled? Is it part of the HTTPServer or somewhere else?

**Comment by rlebeau** [comment]
The wait I'm referring to is the call to `InternalReadLn()` on line 1285 of `IdCustomHTTPServer.pas`, inside of `TIdCustomHTTPServer.DoExecute()`.  That statement is inside a loop reading the 1st line of each new request.  During a server shutdown, `TIdCustomTCPServer.SetActive()` calls `Shutdown()` which calls `TerminateAllThreads()` to close every connected client socket, which SHOULD cause that read (or any subsequent read) to fail, throwing an exception that terminates the thread.  Meanwhile, the server calls the Scheduler's `TerminateAllYarns()` to wait for all of the client threads to fully terminate and release their `TIdYarn` objects. That is where you are getting stuck, because not all of the threads are terminating properly.  So, you really need to debug inside of `TIdCustomHTTPServer.DoExecute()` to see where it is getting stuck during shutdown.

**Comment by rlebeau** [comment]
Any further info on this?

**Comment by SARTrack** [comment]
I had to give it up. I don't understand the code and nobody else wanted to help.

So I had to purchased a new MS-Windows VPS, transferred all live data back from the Linux server (which used a different encryption format, a bloddy nightmare) and I am now totally away from Linux for anything to do with Indy.

Bart
